/**
 * Generated-asset drift report (#308): the read-side upgrade check behind
 * `specgit status`. This module owns NO filesystem rules of its own — it
 * reuses the exact desired-state builders the writers converge
 * (`buildHarnessDesiredState` + the `.gitignore` transform for init,
 * `buildAgentSurfaceDesiredState` for setup) and reads them through the
 * reconciler's `inspectManagedAssets`, so the checklist can never drift
 * from the writer. It never writes, deletes, chmods, prompts, calls
 * gh/glab, or edits provider declarations; the one mutating seam the init
 * writer has (the policy `portWrite`) is simply not built here — policy is
 * authoritative content, not generated bytes.
 *
 * Report contract (stable, machine-facing; names and codes never localize):
 *
 * - per asset: `current` | `stale` | `missing` | `conflict` with codes
 *   `asset_stale` / `asset_missing` / `asset_conflict`;
 * - per surface: `init` → `specgit init --force` (or `specgit init` when
 *   no policy exists yet), `opencode` → `specgit setup --tool opencode`,
 *   `generic` → `specgit setup --tool generic`; an optional setup surface
 *   with nothing on disk is `absent` — clean, no fix, no missing-file
 *   list;
 * - `complete` is the fail-closed completeness claim: true only when
 *   every part of the desired state got a claim (or a proven opt-out in
 *   `skipped`) — "no detected drift" is never "proven clean";
 * - `clean` requires `complete` AND no inspected surface stale/missing/
 *   conflict;
 * - `uninspected` names every desired part NO claim was made about
 *   (undecided platform — including an invalid providers declaration —
 *   unresolved default branch, unmergeable hooks.json, failed probes,
 *   unreadable evidence) — each an unknown that makes the report
 *   incomplete; `skipped` names intentional, proven non-applicability
 *   (the committed-authoritative `.gitignore` opt-out) — proof, not an
 *   unknown, so it never makes a report incomplete. Status never guesses
 *   where the writer itself would guess.
 */

import * as fs from 'node:fs/promises';

import { buildAgentSurfaceDesiredState } from './agent-surface.js';
import {
  buildHarnessDesiredState,
  HARNESS_WORKFLOW_PATH,
  legacyGitHooksDir,
} from './harness-placement.js';
import { harnessWorkflowYaml } from './harness-content.js';
import {
  inspectManagedAssets,
  type ManagedAssetFinding,
  type ManagedAssetState,
} from './managed-reconcile.js';
import { classifyPlatformMode } from './commands/init-platform.js';
import { selectCompletionWorkflow, selectWorkflowYaml } from './commands/init-workflow.js';
import { COMPLETION_WORKFLOW_PATH, GITLAB_COMPLETION_WORKFLOW_PATH } from './completion-workflow.js';
import {
  hasManagedIgnoreRegion,
  reconcileLocalAssetIgnore,
} from './commands/init-ignore.js';
import { resolveLanguage } from './language.js';
import type { Evidence } from '../kernel/evidence.js';
import type { CommandContext, GitFacts, Policy } from './types.js';

export type { ManagedAssetFinding, ManagedAssetState } from './managed-reconcile.js';

/** The three repair surfaces, in report order. */
export type GeneratedSurfaceName = 'init' | 'opencode' | 'generic';

/** A surface's aggregate state: the worst asset state, or `absent`. */
export type GeneratedSurfaceState = ManagedAssetState | 'absent';

/** The exact repair command for one surface; never localized. */
export type GeneratedSurfaceFix =
  | 'specgit init'
  | 'specgit init --force'
  | 'specgit setup --tool opencode'
  | 'specgit setup --tool generic';

export interface GeneratedSurfaceReport {
  surface: GeneratedSurfaceName;
  state: GeneratedSurfaceState;
  /** Present exactly when `state` is `stale`, `missing`, or `conflict`. */
  fix?: GeneratedSurfaceFix;
  /** The per-asset findings this surface's claim rests on. */
  assets: ManagedAssetFinding[];
}

export interface GeneratedAssetsReport {
  /**
   * True only when every required claim is complete AND no inspected
   * surface is stale, missing, or conflicting — the fail-closed upgrade
   * verdict: "no detected drift" is not "proven clean", so an incomplete
   * report never says clean even when every inspected asset matches.
   */
  clean: boolean;
  /**
   * True when every part of the desired state was claimed or proven
   * intentionally skipped. False means at least one part is UNKNOWN
   * (named in `uninspected`) and `current` cannot be proven.
   */
  complete: boolean;
  surfaces: GeneratedSurfaceReport[];
  /**
   * Machine codes for desired parts no claim was made about — each is a
   * documented refusal to guess, never a silently dropped check, and
   * each makes the report incomplete: the desired bytes are unknowable.
   */
  uninspected: string[];
  /**
   * Machine codes for intentional, proven non-applicability (the
   * committed-authoritative `.gitignore` opt-out). A skip is proof, not
   * an unknown: it never makes a report incomplete.
   */
  skipped: string[];
}

/** Repair-severity order for aggregation: conflict blocks, missing breaks, stale ages. */
const SEVERITY: Record<ManagedAssetState, number> = {
  conflict: 3,
  missing: 2,
  stale: 1,
  current: 0,
};

/** The worst per-asset state a surface's findings contain. */
function worstState(findings: ManagedAssetFinding[]): ManagedAssetState {
  return findings.reduce<ManagedAssetState>(
    (worst, finding) => (SEVERITY[finding.state] > SEVERITY[worst] ? finding.state : worst),
    'current'
  );
}

/**
 * A setup surface is installed when anything of SpecGit's naming lives on
 * it — a current entry point OR a retirement candidate. Only a surface
 * with nothing on disk at all is `absent` (#308: an uninstalled optional
 * surface is clean, never a list of missing files).
 */
function surfaceInstalled(findings: ManagedAssetFinding[]): boolean {
  return findings.some((finding) => finding.state !== 'missing');
}

function setupSurface(
  surface: 'opencode' | 'generic',
  findings: ManagedAssetFinding[],
  fix: GeneratedSurfaceFix
): GeneratedSurfaceReport {
  if (!surfaceInstalled(findings)) {
    return { surface, state: 'absent', assets: [] };
  }
  const state = worstState(findings);
  return {
    surface,
    state,
    ...(state !== 'current' ? { fix } : {}),
    assets: findings,
  };
}

/** The tracked probe that distinguishes the committed-authoritative model (#292/#308). */
const AUTHORITATIVE_PATHS = ['.specgit.yaml', 'spec_git/policy.yaml'];

/**
 * Decide whether the `.gitignore` region may be claimed at all. `inspect`
 * when a managed region exists (keep it current) or when the local-asset
 * model applies; otherwise a machine code explaining the refusal: a repo
 * that commits the authoritative tier opted out of the block, and a failed
 * tracked probe means the model is unknowable — never a guessed `missing`.
 * An unreadable `.gitignore` (EISDIR/EACCES/…) is likewise an unknown
 * (#308 Delta 2): only a truly absent path may mean absence, so a read
 * error can never collapse into the proven committed-authoritative skip.
 */
async function ignoreClaim(
  root: string,
  ctx: CommandContext
): Promise<
  'inspect' | 'ignore_committed_authoritative' | 'ignore_tracked_unknown' | 'ignore_unreadable'
> {
  let gitignore: string | null;
  try {
    gitignore = await fs.readFile(`${root}/.gitignore`, 'utf-8');
  } catch (error) {
    // The same absence proof the reconciler's readIfExists uses: ENOENT,
    // or ENOTDIR when a path component is a file. Everything else is
    // unreadable evidence, not a missing file.
    const code = (error as NodeJS.ErrnoException)?.code;
    if (code !== 'ENOENT' && code !== 'ENOTDIR') {
      return 'ignore_unreadable';
    }
    gitignore = null;
  }
  if (hasManagedIgnoreRegion(gitignore)) {
    return 'inspect';
  }
  const trackedEv = await ctx.git.trackedFiles(root, [...AUTHORITATIVE_PATHS]);
  if (!trackedEv.ok) {
    return 'ignore_tracked_unknown';
  }
  return trackedEv.value.length > 0 ? 'ignore_committed_authoritative' : 'inspect';
}

export async function inspectGeneratedAssets(args: {
  root: string;
  ctx: CommandContext;
  /** Already-read configuration determines language and authorized generated assets. */
  policy: Evidence<Policy>;
  facts: GitFacts;
}): Promise<GeneratedAssetsReport> {
  const { root, ctx, policy, facts } = args;
  const uninspected: string[] = [];
  const skipped: string[] = [];
  const language = resolveLanguage(policy.ok ? policy.value : null);

  // ---- init surface: the writer's own desired state, read not written. ----
  // The workflow desire depends on the platform; classifyPlatformMode is
  // the pure/read-only twin of resolvePlatformMode (no persistence, no
  // prompt). `undefined` means NO claim is possible — the desired workflow
  // is unknowable, and the step is dropped below instead of guessed.
  const platform = await classifyPlatformMode(root, facts.originUrl);
  let workflowYaml: string | null | undefined;
  if (platform === 'gitlab') {
    workflowYaml = null; // desired: no GitHub workflow; an owned one is removable
  } else if (platform === 'github') {
    const selection = await selectWorkflowYaml(ctx, root);
    if (selection.warning !== undefined) {
      // The desired bytes would pin a guessed default branch — the writer
      // itself warns and falls back; status refuses to call that drift.
      uninspected.push('workflow_default_branch_unresolved');
    } else {
      workflowYaml = selection.yaml;
    }
  } else {
    // `undecided`: heuristics exhausted, no claim. `providers_invalid`
    // (#308 Delta 2): the authoritative declaration is unreadable as a
    // declaration — same refusal, sharper code, never an origin guess.
    uninspected.push(
      platform === 'providers_invalid'
        ? 'workflow_platform_providers_invalid'
        : 'workflow_platform_undecided'
    );
  }

  const completionEnabled = policy.ok && policy.value.automation?.merge === true;
  const completion = platform === 'providers_invalid' && completionEnabled
    ? { ok: false as const, code: 'automation_platform_unknown' }
    : await selectCompletionWorkflow(ctx, root, platform === 'providers_invalid' ? 'undecided' : platform, completionEnabled);
  if (!completion.ok) uninspected.push(completion.code);
  const harness = await buildHarnessDesiredState(root, {
    resolveHooksDir: async (repoRoot) => {
      const hooksEv = await ctx.git.hooksPath(repoRoot);
      if (!hooksEv.ok && (hooksEv.code === 'git_hooks_external' || hooksEv.code === 'git_hooks_unverified')) {
        (hooksEv.code === 'git_hooks_external' ? skipped : uninspected).push(hooksEv.code);
        return null;
      }
      return hooksEv.ok ? hooksEv.value : legacyGitHooksDir(repoRoot);
    },
    // buildHarnessDesiredState demands a definite workflow desire (bytes or
    // removal); for the no-claim case any bytes stand in and the step is
    // filtered out before inspection — it is never compared, never written.
    workflowYaml: workflowYaml === undefined ? harnessWorkflowYaml() : workflowYaml,
    language,
    completion: completion.ok ? completion.value : null,
  });
  // Harness-builder warnings mark desired steps the writer itself cannot
  // converge (an unmergeable hooks.json): no claim, by code.
  for (const warning of harness.warnings) {
    uninspected.push(warning.code);
  }
  const initSteps = harness.steps.filter((step) =>
    (workflowYaml !== undefined || step.path !== HARNESS_WORKFLOW_PATH) &&
    (completion.ok || (step.path !== COMPLETION_WORKFLOW_PATH && step.path !== GITLAB_COMPLETION_WORKFLOW_PATH)));

  const claim = await ignoreClaim(root, ctx);
  if (claim === 'inspect') {
    initSteps.push({
      kind: 'write',
      path: '.gitignore',
      mode: 0o644,
      merge: (existing) => reconcileLocalAssetIgnore(existing),
    });
  } else if (claim === 'ignore_committed_authoritative') {
    // A proven opt-out, not an unknown: it rides `skipped` and never
    // makes an otherwise current report incomplete.
    skipped.push(claim);
  } else {
    // ignore_tracked_unknown / ignore_unreadable: the region model is
    // unknowable, so no claim — an unknown that fails completeness.
    uninspected.push(claim);
  }

  // ---- setup surfaces: each diagnosed independently (#308). ----
  const opencodeDesired = await buildAgentSurfaceDesiredState(root, 'opencode');
  const genericDesired = await buildAgentSurfaceDesiredState(root, 'generic');
  const [initInspection, opencodeInspection, genericInspection] = await Promise.all([
    inspectManagedAssets(root, { steps: initSteps }),
    inspectManagedAssets(root, { steps: opencodeDesired.steps }),
    inspectManagedAssets(root, { steps: genericDesired.steps }),
  ]);
  // Defensive: this builder never emits portWrite steps, but a future step
  // kind that mutates to inspect must surface here, not vanish.
  const notInspectedPaths = [
    ...initInspection.notInspected,
    ...opencodeInspection.notInspected,
    ...genericInspection.notInspected,
  ];
  for (const path of notInspectedPaths) {
    uninspected.push(`port_write_not_inspected:${path}`);
  }

  const initState = worstState(initInspection.findings);
  const surfaces: GeneratedSurfaceReport[] = [
    {
      surface: 'init',
      state: initState,
      // No policy yet: plain `init` creates it; `--force` is the upgrade
      // repair once the authoritative policy exists.
      ...(initState !== 'current' ? { fix: policy.ok ? 'specgit init --force' : 'specgit init' } : {}),
      assets: initInspection.findings,
    },
    setupSurface('opencode', opencodeInspection.findings, 'specgit setup --tool opencode'),
    setupSurface('generic', genericInspection.findings, 'specgit setup --tool generic'),
  ];

  // Fail-closed completeness (#308 review): only a report with no unknown
  // parts — every desired claim made or proven skipped — may say clean.
  const complete = uninspected.length === 0;
  return {
    clean:
      complete &&
      surfaces.every((surface) => surface.state === 'current' || surface.state === 'absent'),
    complete,
    surfaces,
    uninspected,
    skipped,
  };
}

/**
 * Human rendering of the report (#308): localized labels through the
 * catalog, machine parts (surface names, states, codes, paths, fix
 * commands) verbatim. Pure — status composes the lines it renders.
 */
export function renderGeneratedAssetsHuman(
  report: GeneratedAssetsReport | null,
  text: {
    statusAssetsCurrent(): string;
    statusAssetsDrift(): string;
    statusAssetsIncomplete(): string;
    statusAssetSurface(surface: string, state: string, fix: string): string;
    statusAssetEntry(state: string, path: string): string;
    statusAssetUninspected(code: string): string;
    statusAssetSkipped(code: string): string;
  }
): string[] {
  if (report === null) {
    return []; // the inspection-failure warning already speaks
  }
  if (report.clean) {
    // clean implies complete: the current claim is made only for a full
    // proof. Proven opt-outs still render — proof, not drift.
    return [
      text.statusAssetsCurrent(),
      ...report.skipped.map((code) => text.statusAssetSkipped(code)),
    ];
  }
  const lines: string[] = [];
  const drifted = report.surfaces.filter(
    (surface) => surface.state !== 'current' && surface.state !== 'absent'
  );
  if (drifted.length > 0) {
    lines.push(text.statusAssetsDrift());
    for (const surface of drifted) {
      lines.push(text.statusAssetSurface(surface.surface, surface.state, surface.fix ?? ''));
      for (const asset of surface.assets) {
        if (asset.state === 'current') {
          continue;
        }
        lines.push(text.statusAssetEntry(asset.state, asset.path));
      }
    }
  }
  if (!report.complete) {
    // Incomplete is its own state, never a weakened "current": the
    // uninspected codes name exactly which proof is missing.
    lines.push(text.statusAssetsIncomplete());
    for (const code of report.uninspected) {
      lines.push(text.statusAssetUninspected(code));
    }
  }
  for (const code of report.skipped) {
    lines.push(text.statusAssetSkipped(code));
  }
  return lines;
}
