/**
 * Portable external acceptance harness for `specgit init` (issue #63).
 *
 * The self-hosted template in `harness-assets.ts` assumes the adopting
 * repository IS SpecGit (pnpm, local build, `node bin/specgit.js`, `main`).
 * This module generates the workflow for every other repository: it
 * installs the PUBLISHED SpecGit package at the exact version the running
 * CLI pins, sets up only Node at the supported engine floor, parameterizes
 * the default branch, and invokes the installed CLI — never the adopting
 * project's toolchain, lockfile, layout, or build.
 *
 * Assembled wiring (#63): `specgit init` selects this template for
 * adopting repositories — self-detection (root package name `specgit`)
 * keeps the SpecGit repository itself on the local-build template, which
 * the anti-drift lock in `init.test.ts` pins byte-exactly — and passes
 * `{ defaultBranch: <remote default branch>, version: <CLI version> }`.
 * The generated bytes ride the same error-atomic harness write as every
 * other artifact (#62). GitHub evidence flows exclusively through the
 * authenticated `gh` CLI — including the wait step, which shells out to
 * `gh api` rather than speaking raw REST.
 *
 * Deterministic: identical inputs produce byte-identical output, so a
 * `--force` re-init rewrites the same file and repairs drift (a plain
 * re-init rejects at `policy_exists` before any write, per the #62
 * non-destructive contract).
 */

import * as fs from 'node:fs/promises';
import * as path from 'node:path';

import { HARNESS_WORKFLOW_PATH } from './harness-assets.js';

export interface ExternalHarnessInput {
  /** The adopting repository's remote default branch (e.g. `main`, `master`, `trunk`). */
  defaultBranch: string;
  /** The exact published version to pin and install (no ranges, no tags). */
  version: string;
}

/** Exact semver only: `1.2.3`, optionally with prerelease/build suffixes. */
const EXACT_VERSION = /^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$/;

function assertExactVersion(version: string): void {
  if (typeof version !== 'string' || !EXACT_VERSION.test(version)) {
    throw new Error(
      `External harness: "${version}" is not an exact published version. ` +
        'The gate must pin one version (e.g. 1.2.3), never a range or a tag.'
    );
  }
}

function assertDefaultBranch(defaultBranch: string): void {
  if (typeof defaultBranch !== 'string' || defaultBranch.length === 0 || /\s/.test(defaultBranch)) {
    throw new Error(
      `External harness: "${defaultBranch}" is not a usable branch name. ` +
        'Pass the adopting repository remote default branch, e.g. main or master.'
    );
  }
}

export function externalAcceptanceWorkflowYaml(input: ExternalHarnessInput): string {
  assertDefaultBranch(input.defaultBranch);
  assertExactVersion(input.version);
  return `name: SpecGit Acceptance

on:
  pull_request:
    branches: [${input.defaultBranch}]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  specgit-acceptance:
    name: SpecGit Acceptance
    # Portable gate for any adopting repository: the published CLI is
    # installed at the exact version \`specgit init\` pinned. The adopting
    # project's own toolchain (package manager, lockfile, build, layout)
    # is never assumed and never invoked.
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          # Check out the PR head branch by name so HEAD is on the branch
          # (not the detached merge ref): the execution context gate reads
          # live git. Falls back to the default ref on non-PR events.
          ref: \${{ github.head_ref || github.ref }}
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '20.19'

      - name: Install pinned SpecGit CLI
        # Exact version on purpose (no ^): the gate must evaluate with the
        # same CLI generation that wrote the binding; upgrades are a
        # deliberate re-init. --no-save keeps the adopting tree clean.
        run: npm install --no-save --no-audit --no-fund specgit@${input.version}

      - name: Wait for sibling checks
        # The verdict must see the OTHER required checks in a terminal
        # state. Sibling jobs start in parallel AND may not have registered
        # their check-runs yet, so an empty poll is not "done": wait until
        # every name in spec_git/policy.yaml is present with a terminal
        # conclusion. This job is not in the policy, so no self-deadlock.
        # All GitHub access goes through the authenticated gh CLI.
        env:
          GH_TOKEN: \${{ github.token }}
          WAIT_REPO: \${{ github.repository }}
          WAIT_SHA: \${{ github.event.pull_request.head.sha || github.sha }}
        run: |
          node --input-type=module <<'EOF'
          import { readFileSync } from 'node:fs';
          import { execFileSync } from 'node:child_process';
          import { parse } from 'yaml';
          const policy = parse(readFileSync('spec_git/policy.yaml', 'utf8'));
          const required = policy.required_checks ?? [];
          const listChecks = () =>
            JSON.parse(
              execFileSync(
                'gh',
                [
                  'api',
                  'repos/' + process.env.WAIT_REPO + '/commits/' + process.env.WAIT_SHA + '/check-runs?per_page=100',
                ],
                { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }
              )
            );
          const terminal = new Set(['completed']);
          const terminalHas = (byName, name) => {
            if (byName.has(name)) return terminal.has(byName.get(name));
            const retried = [...byName.keys()].find((k) => k.startsWith(name + ' ('));
            return retried !== undefined && terminal.has(byName.get(retried));
          };
          // Transient API failures (5xx, 429, network) retry with bounded
          // exponential backoff — a platform blip must not fail the gate.
          const MAX_ATTEMPTS = 5;
          const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
          const listChecksWithRetry = async () => {
            for (let attempt = 1; ; attempt += 1) {
              try {
                return listChecks();
              } catch (error) {
                const text = String(error) + ' ' + String(error && error.stderr ? error.stderr : '');
                const transient = /HTTP 5\\d\\d|HTTP 429|ETIMEDOUT|ECONNRESET|ENOTFOUND|timed out/i.test(text);
                if (attempt >= MAX_ATTEMPTS || !transient) throw error;
                const backoff = Math.min(30000, 2000 * 2 ** (attempt - 1));
                console.log('Transient failure; retry ' + attempt + '/' + MAX_ATTEMPTS + ' in ' + backoff + 'ms');
                await sleep(backoff);
              }
            }
          };
          const deadline = Date.now() + 15 * 60 * 1000;
          while (Date.now() < deadline) {
            const payload = await listChecksWithRetry();
            const byName = new Map(payload.check_runs.map((r) => [r.name, r.status]));
            const missing = required.filter((n) => !terminalHas(byName, n));
            if (missing.length === 0) {
              console.log('All required checks are in a terminal state.');
              process.exit(0);
            }
            console.log('Waiting for: ' + missing.join(', '));
            await sleep(10000);
          }
          console.error('Timed out waiting for sibling checks.');
          process.exit(1);
          EOF

      - name: specgit finish
        run: npx --no-install specgit finish --json
        env:
          GH_TOKEN: \${{ github.token }}
`;
}

/**
 * Write (or repair, byte-identically) the external acceptance workflow at
 * the canonical harness path under `root`. Returns the repo-relative path.
 */
export async function writeExternalHarnessWorkflow(
  root: string,
  input: ExternalHarnessInput
): Promise<string> {
  const target = path.join(root, ...HARNESS_WORKFLOW_PATH.split('/'));
  await fs.mkdir(path.dirname(target), { recursive: true });
  await fs.writeFile(target, externalAcceptanceWorkflowYaml(input), 'utf-8');
  return HARNESS_WORKFLOW_PATH;
}
