/**
 * Portable external acceptance harness for `specgit init` (issue #63).
 *
 * The self-hosted template in `harness-content.ts` assumes the adopting
 * repository IS SpecGit (pnpm, local build, `node bin/specgit.js`, `main`).
 * This module generates the workflow for every other repository: it
 * installs the PUBLISHED SpecGit package at the exact version the running
 * CLI pins, sets up only Node at the supported engine floor, parameterizes
 * the default branch, and invokes the installed CLI — never the adopting
 * project's toolchain, lockfile, layout, or build.
 *
 * Assembled wiring (#63): `specgit init` selects this template for
 * adopting repositories — self-detection (root package name `specgit`)
 * keeps the SpecGit repository itself on the local-build template, which
 * the anti-drift lock in `init.test.ts` pins byte-exactly — and passes
 * `{ defaultBranch: <remote default branch>, version: <CLI version> }`.
 * The generated bytes ride the same error-atomic harness write as every
 * other artifact (#62). GitHub evidence flows exclusively through the
 * authenticated `gh` CLI — including the wait step, which shells out to
 * `gh api` rather than speaking raw REST.
 *
 * Deterministic: identical inputs produce byte-identical output, so a
 * `--force` re-init rewrites the same file and repairs drift (a plain
 * re-init rejects at `policy_exists` before any write, per the #62
 * non-destructive contract).
 */

import * as fs from 'node:fs/promises';
import * as path from 'node:path';

import { HARNESS_WORKFLOW_PATH } from './harness-placement.js';
import { ACCEPTANCE_JOB_MINUTES, waitStepYaml } from './wait-step.js';

export interface ExternalHarnessInput {
  /** The adopting repository's remote default branch (e.g. `main`, `master`, `trunk`). */
  defaultBranch: string;
  /** The exact published version to pin and install (no ranges, no tags). */
  version: string;
}

/** Exact semver only: `1.2.3`, optionally with prerelease/build suffixes. */
const EXACT_VERSION = /^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$/;

function assertExactVersion(version: string): void {
  if (typeof version !== 'string' || !EXACT_VERSION.test(version)) {
    throw new Error(
      `External harness: "${version}" is not an exact published version. ` +
        'The gate must pin one version (e.g. 1.2.3), never a range or a tag.'
    );
  }
}

function assertDefaultBranch(defaultBranch: string): void {
  if (typeof defaultBranch !== 'string' || defaultBranch.length === 0 || /\s/.test(defaultBranch)) {
    throw new Error(
      `External harness: "${defaultBranch}" is not a usable branch name. ` +
        'Pass the adopting repository remote default branch, e.g. main or master.'
    );
  }
}

export function externalAcceptanceWorkflowYaml(input: ExternalHarnessInput): string {
  assertDefaultBranch(input.defaultBranch);
  assertExactVersion(input.version);
  return `name: SpecGit Acceptance

on:
  pull_request:
    branches: [${JSON.stringify(input.defaultBranch)}]
    # A draft PR fails the verdict (pr_draft), so the draft→ready
    # transition must re-verdict. Listing types replaces the defaults,
    # so the default activity types are listed alongside. Title and body
    # edits change live acceptance evidence even when the head is unchanged.
    types: [opened, synchronize, reopened, ready_for_review, edited]
  workflow_dispatch:

permissions:
  contents: read
  issues: read
  pull-requests: read
  actions: read

# One verdict per head at a time (#319): a newer trigger event (a push
# after the draft opened, then ready_for_review) supersedes the older
# run of the same pull request instead of leaving parallel copies
# burning identical wait budgets. The surviving run re-verdicts fully.
concurrency:
  group: specgit-accept-\${{ github.ref }}
  cancel-in-progress: true

jobs:
  specgit-acceptance:
    name: SpecGit Acceptance
    # Portable gate for any adopting repository: the published CLI is
    # installed at the exact version \`specgit init\` pinned. The adopting
    # project's own toolchain (package manager, lockfile, build, layout)
    # is never assumed and never invoked.
    runs-on: ubuntu-latest
    timeout-minutes: ${ACCEPTANCE_JOB_MINUTES}
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          # Pin execution to this event; a newer branch push must not change
          # the code tested by an older run. Manual dispatch uses its own SHA.
          ref: \${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 0
          persist-credentials: false

      - name: Restore the event branch
        if: github.event_name == 'pull_request' || github.ref_type == 'branch'
        env:
          SPECGIT_BRANCH: \${{ github.head_ref || github.ref_name }}
        run: |
          git check-ref-format --branch "$SPECGIT_BRANCH" >/dev/null
          git switch --create "$SPECGIT_BRANCH"

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '20.19'
          package-manager-cache: false

      - name: Install pinned SpecGit CLI
        # Exact version on purpose (no ^): the gate must evaluate with the
        # same CLI generation that wrote the binding; upgrades are a
        # deliberate re-init. An isolated prefix avoids installing the
        # adopting project's dependencies or running its lifecycle scripts.
        run: npm install --prefix "$RUNNER_TEMP/specgit-cli" --no-save --no-audit --no-fund specgit@${input.version}

      - name: Prepare approved policy for acceptance
        env:
          GH_TOKEN: \${{ github.token }}
          SPECGIT_WAIT_POLICY: \${{ runner.temp }}/specgit-policy.yaml
        run: |
          gh auth setup-git
          node "$RUNNER_TEMP/specgit-cli/node_modules/specgit/dist/automation/workflow-policy.js"

${waitStepYaml('gh')}

      - name: specgit finish
        run: '"$RUNNER_TEMP/specgit-cli/node_modules/.bin/specgit" finish --json'
        env:
          GH_TOKEN: \${{ github.token }}
`;
}

/**
 * Write (or repair, byte-identically) the external acceptance workflow at
 * the canonical harness path under `root`. Returns the repo-relative path.
 */
export async function writeExternalHarnessWorkflow(
  root: string,
  input: ExternalHarnessInput
): Promise<string> {
  const target = path.join(root, ...HARNESS_WORKFLOW_PATH.split('/'));
  await fs.mkdir(path.dirname(target), { recursive: true });
  await fs.writeFile(target, externalAcceptanceWorkflowYaml(input), 'utf-8');
  return HARNESS_WORKFLOW_PATH;
}
