/**
 * State/asset taxonomy (#69): how everything `specgit` writes is classified.
 *
 * Three tiers, one rule each:
 * - authoritative committed files carry the product state itself; they are
 *   the source of truth and are edited (rarely) by humans or by explicit
 *   commands, never regenerated;
 * - derived committed harness is generated by `specgit init` and committed;
 *   drift is repaired by regenerating (`init --force`), not hand-editing;
 * - local integration assets are guard hooks written by `specgit init`
 *   and per-tool entry points written by `specgit setup`; these agent
 *   conveniences carry no acceptance meaning.
 */

export interface StateAssetTier {
  description: string;
  paths: string[];
}

export const STATE_ASSET_TAXONOMY = {
  authoritativeCommitted: {
    description:
      'Committed source-of-truth files: the project policy, the platform declarations, and the delivery record.',
    paths: ['spec_git/policy.yaml', 'spec_git/providers.yaml', '.specgit.yaml'],
  },
  derivedCommittedHarness: {
    description:
      'Committed harness generated by specgit init; regenerate (init --force) instead of hand-editing.',
    paths: [
      '.github/workflows/specgit-accept.yml',
      'AGENTS.md (specgit managed block)',
      'CLAUDE.md (specgit managed block, when present)',
    ],
  },
  localIntegrationAssets: {
    description:
      'Local guard hooks written by specgit init and per-tool entry points written by specgit setup; agent conveniences, never acceptance inputs.',
    paths: [
      '.opencode/hooks.json (specgit guard entry)',
      '.opencode/hooks/specgit-merge-guard.sh',
      'git pre-push hook (specgit managed markers)',
      '.opencode/command/specgit-issue.md',
      '.opencode/command/specgit-finish.md',
      '.opencode/command/specgit-doctor.md',
      '.opencode/command/specgit-pr.md',
      '.opencode/command/specgit-status.md',
      '.agents/skills/specgit-issue/SKILL.md',
      '.agents/skills/specgit-finish/SKILL.md',
      '.agents/skills/specgit-doctor/SKILL.md',
      '.agents/skills/specgit-pr/SKILL.md',
      '.agents/skills/specgit-status/SKILL.md',
    ],
  },
} as const satisfies Record<string, StateAssetTier>;

export type StateAssetTaxonomy = typeof STATE_ASSET_TAXONOMY;
